Author: Dominik George <nik@naturalnet.de>
Description: Makes the Makefile accept variables from outside
Forwarded: no

--- a/Makefile
+++ b/Makefile
@@ -1,17 +1,17 @@
 EXE		= morse2ascii
-CFLAGS	+= -O2 -s
-PREFIX	= /usr/local
-BINDIR	= $(PREFIX)/bin
+BINDIR	= $(DESTDIR)/usr/bin
 LIBS	= -lm
 
 all:
-	$(CC) $(CFLAGS) -c morse2ascii.c
-	$(CC) $(CFLAGS) -c resample2.c
-	$(CC) $(CFLAGS) -o $(EXE) $(LIBS) morse2ascii.o resample2.o
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c morse2ascii.c
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c resample2.c
+	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $(EXE) morse2ascii.o resample2.o $(LIBS)
 
 install:
 	install -m 755 -d $(BINDIR)
 	install -m 755 $(EXE) $(BINDIR)/$(EXE)
 
-.PHONY:
-	install
+clean:
+	rm -f morse2ascii *.o
+
+.PHONY: install all clean
